- name: vars
  hosts: local
  connection: local
  vars:
    COURSE: ansible
    DURATION: 10hrs
    TRAINER: Siva
  tasks:
  - name: vars
    ansible.builtin.debug:
      msg: "course is {{COURSE}},duration is {{DURATION}} and trainer is {{TRAINER}}"